services:
  restaurant:
    build:
      context: ./backend/restaurant
    environment:
      - API_KEY=c6b8b816c8991a66d1964bb6a0012be3
    ports:
      - "8000:80" # Port host:port container
    container_name: restaurant
    command: uvicorn main:app --host 0.0.0.0 --port 80

  menu:
    build:
      context: ./backend/menu
    environment:
      - API_KEY=c6b8b816c8991a66d1964bb6a0012be3
    ports:
      - "8001:80" # Pemetaan port host ke port internal
    container_name: menu
    command: uvicorn main:app --host 0.0.0.0 --port 80

  delivery:
    build:
      context: ./backend/delivery
    environment:
      - API_KEY=c6b8b816c8991a66d1964bb6a0012be3
    ports:
      - "8002:80" # Pemetaan port host ke port internal
    container_name: delivery
    command: uvicorn main:app --host 0.0.0.0 --port 80
