services:
  restaurant:
    build:
      context: ./backend/restaurant
    ports:
      - "8000:80" # Port host:port container
    container_name: restaurant
    command: uvicorn main:app --host 0.0.0.0 --port 80

  menu:
    build:
      context: ./backend/menu
    ports:
      - "8001:80" # Pemetaan port host ke port internal
    container_name: menu
    command: uvicorn main:app --host 0.0.0.0 --port 80

  delivery:
    build:
      context: ./backend/delivery
    ports:
      - "8002:80" # Pemetaan port host ke port internal
    container_name: delivery
    command: uvicorn main:app --host 0.0.0.0 --port 80
